#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.userdemo.domian
  mapperLocations: classpath:mapper/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;databasename=HDPJ
    username: sa
    password: 111111
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

# 使用druid数据源
type: com.alibaba.druid.pool.DruidDataSource
